apiVersion: v1
kind: Service
metadata:
  name: nginx-stable
  labels:
    app: nginx-rollout
spec:
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-canary
  labels:
    app: nginx-rollout
spec:
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80
